name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV     
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force